"""Unit and integration tests for ai_engine.reviser."""

import json
import pytest

from ai_engine.reviser import build_paper
from shared.schemas import GenerateRequest, Question, RetrievedItem, RetrievalResult


@pytest.fixture(scope="module")
def sample_questions():
    """Load 3 random single choice questions from real question bank."""
    import hashlib
    import random
    from datetime import datetime, timezone
    with open("data/chapters/shanghai_2021_yimo.json", "r", encoding="utf-8") as f:
        raw = json.load(f)
    single_choice = [q for q in raw if q.get("question_type") == "single_choice"]
    random.shuffle(single_choice)
    questions = []
    for q in single_choice[:3]:
        if "stem_hash" not in q:
            stem_text = q.get("stem", "") or ""
            q["stem_hash"] = hashlib.md5(stem_text.encode()).hexdigest()
        if "created_at" not in q:
            q["created_at"] = datetime.now(timezone.utc)
        questions.append(Question(**q))
    print(f"\n本次测试随机选择题目ID: {[q.id for q in questions]}")
    return questions


@pytest.fixture(scope="module")
def retrieval_result(sample_questions):
    """Create a retrieval result with the sample questions."""
    return RetrievalResult(items=[
        RetrievedItem(question=q, score=0.9) for q in sample_questions
    ])


def _print_question_comparison(original: Question, revised, index: int):
    """Print comparison between original and revised question."""
    print(f"\n--- 题目 {index} 对比 ---")
    print(f"溯源ID: {original.id}")
    print(f"\n【原题】")
    if original.stem:
        print(f"  题干: {original.stem[:80]}{'...' if len(original.stem) > 80 else ''}")
    else:
        print(f"  题干: (无)")
    if original.options:
        for opt in original.options:
            print(f"  {opt.label}. {opt.text}")
    print(f"  答案: {original.answer}")
    print(f"  知识点: {original.knowledge_point_ids}")
    
    print(f"\n【修改后】")
    if revised.stem:
        print(f"  题干: {revised.stem[:80]}{'...' if len(revised.stem) > 80 else ''}")
    else:
        print(f"  题干: (无)")
    if revised.options:
        for opt in revised.options:
            print(f"  {opt.label}. {opt.text}")
    else:
        print(f"  选项: (无)")
    print(f"  答案: {revised.answer}")
    print(f"  知识点: {revised.knowledge_point_ids}")
    
    is_same_stem = original.stem == revised.stem
    is_same_options = str([(o.label, o.text) for o in original.options or []]) == str([(o.label, o.text) for o in revised.options or []])
    is_same_answer = original.answer == revised.answer
    
    print(f"\n【对比结果】")
    print(f"  题干相同: {'✅' if is_same_stem else '❌'}")
    print(f"  选项相同: {'✅' if is_same_options else '❌'}")
    print(f"  答案相同: {'✅' if is_same_answer else '❌'}")


def test_original_mode(retrieval_result):
    """Test original mode - questions should be copied without modification."""
    req = GenerateRequest(
        mode="fresh",
        question_types=["single_choice"],
        total_questions=3,
        revision_intensity="original",
        free_text="测试 original 模式",
    )
    paper = build_paper(req, retrieval_result)

    assert "原题" in paper.title
    assert len(paper.items) == 3
    assert paper.total_score == 6
    assert paper.metadata["llm_calls"] == 0
    assert len(paper.metadata["revision_failures"]) == 0

    for item in paper.items:
        assert item.revision_mode == "original"
        assert item.source_question_id is not None
        assert item.revision_notes is None

    print(f"\n{'='*70}")
    print(f"ORIGINAL 模式 - 原题直接复制，无修改")
    print(f"{'='*70}")
    for i, item in enumerate(paper.items):
        original_q = next(ri.question for ri in retrieval_result.items if ri.question.id == item.source_question_id)
        _print_question_comparison(original_q, item.question, i + 1)


def test_light_mode(retrieval_result):
    """Test light mode - questions should be slightly modified by LLM."""
    req = GenerateRequest(
        mode="fresh",
        question_types=["single_choice"],
        total_questions=3,
        revision_intensity="light",
        free_text="测试 light 模式",
    )
    paper = build_paper(req, retrieval_result)

    assert "练习" in paper.title
    assert len(paper.items) == 3
    assert paper.metadata["llm_calls"] >= 0
    assert all(item.revision_mode == "light" for item in paper.items)

    print(f"\n{'='*70}")
    print(f"LIGHT 模式 - LLM 轻度修改，保持原题结构")
    print(f"{'='*70}")
    for i, item in enumerate(paper.items):
        original_q = next(ri.question for ri in retrieval_result.items if ri.question.id == item.source_question_id)
        _print_question_comparison(original_q, item.question, i + 1)


def test_fresh_mode(retrieval_result):
    """Test fresh mode - questions should be completely regenerated by LLM."""
    req = GenerateRequest(
        mode="fresh",
        question_types=["single_choice"],
        total_questions=3,
        revision_intensity="fresh",
        free_text="测试 fresh 模式",
    )
    paper = build_paper(req, retrieval_result)

    assert "新题" in paper.title
    assert len(paper.items) == 3
    assert paper.metadata["llm_calls"] >= 0
    assert all(item.revision_mode == "fresh" for item in paper.items)

    print(f"\n{'='*70}")
    print(f"FRESH 模式 - LLM 完全重写，仅保持知识点和题型")
    print(f"{'='*70}")
    for i, item in enumerate(paper.items):
        original_q = next(ri.question for ri in retrieval_result.items if ri.question.id == item.source_question_id)
        _print_question_comparison(original_q, item.question, i + 1)


def test_revision_invariants(retrieval_result):
    """Test that question_type and knowledge_point_ids are preserved after revision."""
    req = GenerateRequest(
        mode="fresh",
        question_types=["single_choice"],
        total_questions=3,
        revision_intensity="light",
        free_text="测试不变量",
    )
    paper = build_paper(req, retrieval_result)

    original_kps = [ri.question.knowledge_point_ids for ri in retrieval_result.items]
    original_qts = [ri.question.question_type for ri in retrieval_result.items]

    for i, item in enumerate(paper.items):
        assert item.question.question_type == original_qts[i]
        assert set(item.question.knowledge_point_ids) == set(original_kps[i])


def test_answer_format_validation(retrieval_result):
    """Test that answer format is correct for single choice questions."""
    req = GenerateRequest(
        mode="fresh",
        question_types=["single_choice"],
        total_questions=3,
        revision_intensity="original",
        free_text="测试答案格式",
    )
    paper = build_paper(req, retrieval_result)

    for item in paper.items:
        assert item.question.answer in {"A", "B", "C", "D"}
        assert item.question.options is not None
        assert len(item.question.options) == 4
        labels = {opt.label for opt in item.question.options}
        assert labels == {"A", "B", "C", "D"}